### ISSUE TITLE
Feature request: allow to set values

### ISSUE THREAD

**Issue by mkj28** [chartmuseum/helm-push#18] opened 2018-10-04 19:51 UTC
Similar to how we can set version, would be nice to be able to set other values,
allowing for something like:
`helm push mychart/ --version="1.2.3" --set image.tag="1.2.3" --set image.imagePullPolicy="Always" chartmuseum` etc.

the packaged chart would have the values set

**Comment by jdolitsky** [comment] 2018-10-04 21:02
@mkj28 please see the discussion here: https://github.com/helm/helm/issues/3141

we can probably make it work in helm-push without worrying about the yaml comments, or maybe its something we can solve in Helm?

**Comment by jdolitsky** [comment] 2019-12-17 04:53
duplicate of updated ticket https://github.com/chartmuseum/helm-push/issues/38

**Closed by jdolitsky** 2019-12-17 04:53 UTC
