### ISSUE TITLE
helm v3  repo add chartmuseum auth failed, unsupported protocol scheme "cm"

### ISSUE THREAD

**Issue by guoweikuang** [chartmuseum/helm-push#36] opened 2019-08-21 09:31 UTC
I am running a ChartMuseum that needs to be authenticated locally. When using helm v3 for repo add, I get an error message. The error message is 
```
➜ repo add chartmuseum cm://localhost:8089 --debug
Error: looks like "cm://localhost:8089" is not a valid chart repository or cannot be reached: Get cm://localhost:8089/index.yaml: unsupported protocol scheme "cm"
helm.go:76: [debug] Get cm://localhost:8089/index.yaml: unsupported protocol scheme "cm"
looks like "cm://localhost:8089" is not a valid chart repository or cannot be reached
main.addRepository
        /go/src/helm.sh/helm/cmd/helm/repo_add.go:108
main.(*repoAddOptions).run
        /go/src/helm.sh/helm/cmd/helm/repo_add.go:73
main.newRepoAddCmd.func1
        /go/src/helm.sh/helm/cmd/helm/repo_add.go:57
helm.sh/helm/vendor/github.com/spf13/cobra.(*Command).execute
        /go/src/helm.sh/helm/vendor/github.com/spf13/cobra/command.go:762
helm.sh/helm/vendor/github.com/spf13/cobra.(*Command).ExecuteC
        /go/src/helm.sh/helm/vendor/github.com/spf13/cobra/command.go:850
helm.sh/helm/vendor/github.com/spf13/cobra.(*Command).Execute
        /go/src/helm.sh/helm/vendor/github.com/spf13/cobra/command.go:800
main.main
        /go/src/helm.sh/helm/cmd/helm/helm.go:75
runtime.main
        /usr/local/go/src/runtime/proc.go:200
runtime.goexit
        /usr/local/go/src/runtime/asm_amd64.s:1337

```
**I guess helm push is not compatible with the use of helm v3**

Is there any plan for this helm v3 compatibility?

**Comment by JulienBreux** [comment] 2019-11-12 11:39
Protocole `cm` is added with the Helm Push plugin ;)

Please re-add pluging ; `helm plugin install https://github.com/chartmuseum/helm-push`

And check if it's ok ; `helm plugin list`

**Comment by jdolitsky** [comment] 2019-12-14 21:17
Closing as duplicate of https://github.com/chartmuseum/helm-push/issues/37

**Closed by jdolitsky** 2019-12-14 21:17 UTC
